import { describe,expect,it } from 'vitest';
import { applyInference,inferBrief,interpretBriefV3 } from './inferBrief';
import type { Questionnaire } from '../types';

describe('inferBrief',()=>{
  it('turns a written use case into checklist values',()=>{const result=inferBrief('Outdoor hinge that is opened repeatedly and gets knocked','accurate fit and weather resistant');expect(result.environment.value).toBe('outdoor');expect(result.load.value).toBe('cyclic');expect(result.impact.value).toBe('medium');expect(result.priority.value).toBe('accuracy')});
  it('preserves manual overrides',()=>{const answers={environment:'indoor'} as Questionnaire;const result=applyInference(answers,inferBrief('outdoor bracket',''),new Set(['environment']));expect(result.environment).toBe('indoor')});
  it('keeps fields unknown when the user supplied no evidence',()=>{const result=inferBrief('','');expect(result.environment.value).toBe('unknown');expect(result.load.value).toBe('unknown');expect(result.impact.value).toBe('unknown');expect(result.priority.value).toBe('unknown');expect(result.supportsAllowed.value).toBe('unknown')});
  it('recognizes explicit Swedish requirements',()=>{const result=inferBrief('Bärande fäste utomhus med upprepad rörelse utan stöd','');expect(result.environment.value).toBe('outdoor');expect(result.load.value).toBe('cyclic');expect(result.priority.value).toBe('strength');expect(result.supportsAllowed.value).toBe(false)});
  it('does not treat a negated outdoor phrase as outdoor evidence',()=>{const result=interpretBriefV3('Indoor bracket, not used outside','');expect(result.inference.environment.value).toBe('indoor');expect(result.conflicts).toHaveLength(0)});
  it('uses the maximum explicit Celsius temperature as the material requirement',()=>{const result=interpretBriefV3('Protective cover used from 20-65 C','');expect(result.temperaturesC).toEqual(expect.arrayContaining([20,65]));expect(result.inference.heat).toMatchObject({value:'warm',confidence:.98})});
  it('keeps conflicting requirements unresolved instead of picking a keyword winner',()=>{const result=interpretBriefV3('Used both indoors and outdoors','');expect(result.inference.environment.value).toBe('unknown');expect(result.conflicts[0]).toMatchObject({field:'environment',values:expect.arrayContaining(['indoor','outdoor'])})});
  it('marks vague heat context as ambiguous rather than assigning a temperature band',()=>{const result=interpretBriefV3('Distance outside heat sun','');expect(result.inference.environment.value).toBe('outdoor');expect(result.inference.heat.value).toBe('unknown');expect(result.ambiguities).toContainEqual(expect.objectContaining({field:'heat'}))});
  it('treats terse heat and sun wording as solar exposure but not a known temperature',()=>{const result=interpretBriefV3('heat sun','');expect(result.inference.environment.value).toBe('outdoor');expect(result.inference.heat.value).toBe('unknown');expect(result.ambiguities).toContainEqual(expect.objectContaining({field:'heat',evidence:expect.arrayContaining(['heat','sun'])}))});
  it('recognizes mixed Swedish and English phrases with word boundaries',()=>{const result=interpretBriefV3('Utomhusfäste, repeated movement, inga slag och supports are fine','');expect(result.inference.environment.value).toBe('outdoor');expect(result.inference.load.value).toBe('cyclic');expect(result.inference.impact.value).toBe('none');expect(result.inference.supportsAllowed.value).toBe(true)});
});
