import { describe, expect, it } from 'vitest';
import { extractModelMetadata } from './stl';

const asciiBuffer = (solidName: string) => new TextEncoder().encode(
  `solid ${solidName}\nfacet normal 0 0 1\nouter loop\nvertex 0 0 0\nvertex 1 0 0\nvertex 0 1 0\nendloop\nendfacet\nendsolid ${solidName}\n`,
).buffer as ArrayBuffer;

const binaryBuffer = (header: string) => {
  const bytes = new Uint8Array(84 + 50);
  bytes.set(new TextEncoder().encode(header).subarray(0, 80));
  new DataView(bytes.buffer).setUint32(80, 1, true);
  return bytes.buffer;
};

describe('model metadata extraction', () => {
  it('uses an ASCII solid name and removes filename revision noise', () => {
    const metadata = extractModelMetadata(asciiBuffer('Phone Stand V2'), 'phone_stand_final_v7.stl');
    expect(metadata.encoding).toBe('ascii');
    expect(metadata.clues).toEqual([
      { source: 'stl-solid-name', value: 'phone stand' },
      { source: 'file-name', value: 'phone stand' },
    ]);
  });

  it('extracts a semantic binary header without exporter boilerplate', () => {
    const metadata = extractModelMetadata(binaryBuffer('Wall Bracket generated by Fusion 360'), 'wall_bracket_copy2.stl');
    expect(metadata.encoding).toBe('binary');
    expect(metadata.clues).toEqual([
      { source: 'stl-binary-header', value: 'wall bracket' },
      { source: 'file-name', value: 'wall bracket' },
    ]);
  });

  it('does not turn generic exporter text or UUID filenames into object claims', () => {
    const metadata = extractModelMetadata(binaryBuffer('Binary STL exported by OpenSCAD'), '019f5db6-9e62-7d10-8794-8255e5943eb1.stl');
    expect(metadata.clues).toEqual([]);
  });

  it('removes directories and personal path segments from an embedded header', () => {
    const metadata = extractModelMetadata(binaryBuffer('C:\\Users\\Alice\\phone_holder.stl'), 'export.stl');
    expect(metadata.clues).toEqual([{ source: 'stl-binary-header', value: 'phone holder' }]);
  });
});
